// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
  getSize: () => Promise<{ width: number; height: number }>;
}

interface ElectronBackend {
  getBackendUrl: () => Promise<string | null>;
  healthCheck: () => Promise<boolean>;
  restartBackend: () => Promise<{ port: number; url: string }>;
}

interface ElectronAPI {
  showOpenDialog: (options: Electron.OpenDialogOptions) => Promise<Electron.OpenDialogReturnValue>;
  showSaveDialog: (options: Electron.SaveDialogOptions) => Promise<Electron.SaveDialogReturnValue>;
  readCsvPreview: (filePath: string, numRows?: number) => Promise<{ headers: string[]; rows: string[][]; delimiter: string }>;
  // IPC communication methods
  send: (channel: string, data: any) => void;
  on: (channel: string, listener: (event: any, data: any) => void) => void;
  off: (channel: string, listener: (event: any, data: any) => void) => void;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  electronBackend: ElectronBackend;
  electronAPI: ElectronAPI;
  autoGrpc: import('./grpc-auto/auto-context').AutoGrpcContext;
}
