// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
  getSize: () => Promise<{ width: number; height: number }>;
}

interface RestApiResponse<T> {
  data: T;
  responseTime: number;
  networkPayloadSize: number;
  frontendMemorySize: number;
  parsingTime: number;
  transmissionTime: number;
}

interface ElectronBackend {
  getBackendUrl: () => Promise<string | null>;
  healthCheck: () => Promise<boolean>;
  restartBackend: () => Promise<{ port: number; url: string }>;
  
  // REST API calls through IPC for fair performance comparison
  rest: {
    healthCheck: () => Promise<RestApiResponse<any>>;
    helloWorld: (request: { message: string }) => Promise<RestApiResponse<{ message: string }>>;
    echoParameter: (request: { value: number; operation: string }) => Promise<RestApiResponse<{ 
      original_value: number; 
      processed_value: number; 
      operation: string 
    }>>;
    getColumnarData: (request: { data_types: string[]; max_points: number }) => Promise<RestApiResponse<{
      data: number[];
      total_count: number;
      bounds: {
        x: { min_value: number; max_value: number };
        y: { min_value: number; max_value: number };
        z: { min_value: number; max_value: number };
      };
      generated_at: number;
    }>>;
    getProjects: () => Promise<RestApiResponse<{ projects: any[] }>>;
    createProject: (request: { name: string; description: string }) => Promise<RestApiResponse<{ project: any }>>;
    getProject: (projectId: string) => Promise<RestApiResponse<{ project: any }>>;
    updateProject: (projectId: string, request: { name: string; description: string }) => Promise<RestApiResponse<{ project: any }>>;
    deleteProject: (projectId: string) => Promise<RestApiResponse<{ success: boolean }>>;
  };
}

interface ElectronAPI {
  showOpenDialog: (options: Electron.OpenDialogOptions) => Promise<Electron.OpenDialogReturnValue>;
  showSaveDialog: (options: Electron.SaveDialogOptions) => Promise<Electron.SaveDialogReturnValue>;
  // IPC communication methods
  send: (channel: string, data: any) => void;
  on: (channel: string, listener: (event: any, data: any) => void) => void;
  off: (channel: string, listener: (event: any, data: any) => void) => void;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  electronBackend: ElectronBackend;
  electronAPI: ElectronAPI;
  autoGrpc: import('./grpc-auto/auto-context').AutoGrpcContext;
}
